import { Navigation } from "@/components/Navigation";
import Footer from "@/components/Footer";

const AcceptableUsePolicy = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-grow container mx-auto px-4 py-24">
        <article className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold mb-8">ProBound Acceptable Use Policy</h1>
          <p className="text-gray-600 mb-8">Last Revised on January 31, 2025</p>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
              <p>
                This Acceptable Use Policy ("Policy") supplements the ProBound Terms of Service and governs your access to and use of our Services, including the inputs you provide (e.g., voice recordings, text prompts, or other data) and your use of outputs generated by our AI-driven voice agent platform (collectively, the "Services"). This Policy is intended to ensure that our Services—and any content or outputs generated through them—are used in a safe, respectful, and lawful manner while respecting the rights of others. This Policy applies to all users, customers, and any third parties authorized to access the Services on a customer's behalf.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Prohibitions</h2>
              <p>You are prohibited from using our Services, or creating/transmitting content (including outputs) via our Services, for any of the following purposes:</p>
              
              <div className="space-y-6 mt-4">
                <div>
                  <h3 className="text-xl font-semibold mb-3">a. Deceptive, Inaccurate, or Misleading Content or Activity</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Impersonation: Do not impersonate any person (including celebrities) or business. You may only submit your own voice, audio recordings, or those of others if you have obtained explicit consent. You are solely responsible for ensuring you have all necessary rights and consents for any inputs provided.</li>
                    <li>Disinformation and Inauthentic Behavior: Do not participate in disinformation campaigns or engage in any activity that is designed to create or spread false or misleading information.</li>
                    <li>Misinformation: Do not create or distribute content that you know, or should reasonably know, is inaccurate or misleading.</li>
                    <li>Promotion of False Information: Do not promote, endorse, or facilitate the spread of false information.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-semibold mb-3">b. Illegal, Abusive, or Fraudulent Content or Activity</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Rights Violations: Do not use the Services in any manner that violates another individual's rights, including privacy, intellectual property, or publicity rights.</li>
                    <li>Defamation: Do not publish or transmit defamatory content against any individual or business.</li>
                    <li>Unlawful Activities: Do not use the Services to promote or facilitate any illegal activities, including criminal conduct.</li>
                    <li>Interference: Do not use the Services to interfere with, disrupt, or negatively impact the functionality or integrity of the Services.</li>
                    <li>Unqualified Professional Advice: Do not use the Services to provide legal, medical, or financial advice if you lack the necessary qualifications.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-semibold mb-3">c. Minor Exploitation, Abuse, or Harm</h3>
                  <p>Do not use the Services to create or transmit content that exploits, abuses, or harms minors. This includes any output that, in our sole discretion, relates to or appears to involve individuals under the age of 18.</p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold mb-3">d. Political or Election-Related Misuse</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Political Campaigning and Lobbying: Do not use the Services for political campaigning, lobbying, fundraising, or solicitation of donations.</li>
                    <li>Election Disinformation: Do not create or share content intended to mislead voters, discourage voting, impersonate political candidates or government officials, or engage in any disinformation campaigns related to the political or election process.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-semibold mb-3">e. Psychologically or Emotionally Harmful Content</h3>
                  <p>Do not use the Services to produce content that shames, humiliates, bullies, or harasses individuals.</p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold mb-3">f. Violent, Hateful, or Threatening Content or Activity</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Violence and Terrorism: Do not threaten or promote violence or terrorism.</li>
                    <li>Encouraging Violence: Do not describe or encourage violent acts against people, animals, or property.</li>
                    <li>Hate Speech and Discrimination: Do not promote hate speech or discrimination based on attributes such as race, religion, gender, age, nationality, or sexual orientation.</li>
                    <li>Undermining Democratic Processes: Do not threaten or undermine democratic processes or institutions.</li>
                    <li>Other Objectionable Content: Any other content that, in our sole discretion, contradicts our values or is deemed objectionable is prohibited.</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. Enforcement</h2>
              <p>Failure to adhere to this Policy may result in one or more of the following actions, at our sole discretion:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>A warning or request to modify your behavior;</li>
                <li>Suspension or termination of your account and access to the Services; or</li>
                <li>Any other actions deemed necessary to protect the integrity of our Services and the rights of others.</li>
              </ul>
              <p className="mt-4">By accessing or using the Services, you agree to comply with this Policy.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Updates and Changes to This Policy</h2>
              <p>
                We may revise this Policy from time to time in response to technical advancements, societal changes, legal requirements, or user feedback. Any updates will take effect immediately upon being posted on this page. Your continued use of the Services after the posting of any changes constitutes your acceptance of the updated Policy. We encourage you to review this Policy periodically.
              </p>
            </section>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
};

export default AcceptableUsePolicy;